// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE93AFDelnpShG5HcnagvViLlbca6x3Ls',
    appId: '1:501276131931:web:5de28b4c9b45e73b8b357e',
    messagingSenderId: '501276131931',
    projectId: 'orbital-best-app',
    authDomain: 'orbital-best-app.firebaseapp.com',
    storageBucket: 'orbital-best-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9S92HFxawsGjATa_TURtfMBl7eiLnf4c',
    appId: '1:501276131931:android:b84650ebe6b4d7818b357e',
    messagingSenderId: '501276131931',
    projectId: 'orbital-best-app',
    storageBucket: 'orbital-best-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7jvEBB1VNm6bDRsVpipD_iJ0SaGnPlG4',
    appId: '1:501276131931:ios:407972f7551bec6d8b357e',
    messagingSenderId: '501276131931',
    projectId: 'orbital-best-app',
    storageBucket: 'orbital-best-app.appspot.com',
    iosClientId: '501276131931-n96n9b3a8ei9hunfnpumg51ccr1ve4ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.orbitalTestSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7jvEBB1VNm6bDRsVpipD_iJ0SaGnPlG4',
    appId: '1:501276131931:ios:407972f7551bec6d8b357e',
    messagingSenderId: '501276131931',
    projectId: 'orbital-best-app',
    storageBucket: 'orbital-best-app.appspot.com',
    iosClientId: '501276131931-n96n9b3a8ei9hunfnpumg51ccr1ve4ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.orbitalTestSpace',
  );
}
